# ----- hr_visualize.py -----
# 3rd Part of the HR data processing pipeline
# --------------------------------------------------------------
# Visualizes event-related Heart Rate (HR) features extracted
# in the previous analysis stage. 
#
# NOTE: CHANGE the Subject ID before running!
#
# Requires:
#   - The analysed HR CSV file generated by hr_event_analysis.py
#
# Generates:
#   1. Mean HR by Event bar chart.
#   2. Max HR by Event bar chart.
#   3. Change from Baseline by Event bar chart.
#
#
# Author: Tuuli Palomäki
# Created: 11 / 11 / 2025
# --------------------------------------------------------------

import os
import pandas as pd
import matplotlib.pyplot as plt

# ------ Settings ------
subject_id = 7  # NOTE CHANGE subject ID 

# ------ Paths ------
script_dir = os.path.dirname(os.path.abspath(__file__))
analysed_path = os.path.join(script_dir, "analysed_data", f"hr_subject{subject_id}_event_features.csv")

print("[PATH] Analysed file:", analysed_path)

# Read analysed HR CSV file
features = pd.read_csv(analysed_path)
print("Available columns:", list(features.columns))

# --------- Visualization helper ---------
def add_value_labels(ax, spacing=3, fmt="{:.1f}"):
    """Add data labels to each bar in a bar chart."""
    for rect in ax.patches:
        height = rect.get_height()
        ax.text(
            rect.get_x() + rect.get_width() / 2,
            height - spacing if height > 0 else height + spacing,
            fmt.format(height),
            ha="center", va="bottom" if height > 0 else "top",
            fontsize=9, color="black"
        )

# --------- Visualization ------

# Figure 1: Mean HR by Event
if "Mean_HR" in features.columns:
    plt.figure(figsize=(10, 6))
    bar_width = 0.6 if len(features) < 15 else 0.4
    bars = plt.bar(features["Event"], features["Mean_HR"], color='lightcoral', width=bar_width)
    plt.title(f"Subject {subject_id} – Mean Heart Rate by Event")
    plt.xlabel("Event Name")
    plt.ylabel("Mean HR (BPM)")
    plt.xticks(rotation=70)
    add_value_labels(plt.gca(), spacing=2)
    plt.tight_layout()
    plt.show()
else:
    print("[WARN] Column 'Mean_HR' not found – skipping plot 1.")

# Figure 2: Max HR by Event
if "Max_HR" in features.columns:
    plt.figure(figsize=(10, 6))
    bars = plt.bar(features["Event"], features["Max_HR"], color='salmon')
    plt.title(f"Subject {subject_id} – Maximum Heart Rate by Event")
    plt.xlabel("Event Name")
    plt.ylabel("Max HR (BPM)")
    plt.xticks(rotation=70)
    add_value_labels(plt.gca(), spacing=2)
    plt.tight_layout()
    plt.show()
else:
    print("[WARN] Column 'Max_HR' not found – skipping plot 2.")

# Figure 3: Change from Baseline by Event
if "Change_from_Baseline" in features.columns:
    plt.figure(figsize=(10, 6))
    bars = plt.bar(features["Event"], features["Change_from_Baseline"], color='lightblue')
    plt.title(f"Subject {subject_id} – HR Change from Baseline by Event")
    plt.xlabel("Event Name")
    plt.ylabel("ΔHR (BPM vs. baseline)")
    plt.axhline(y=0, color='gray', linestyle='--', alpha=0.7)
    plt.xticks(rotation=70)
    add_value_labels(plt.gca(), spacing=0.5, fmt="{:+.1f}")
    plt.tight_layout()
    plt.show()
else:
    print("[WARN] Column 'Change_from_Baseline' not found – skipping plot 3.")
